/** @format */

const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });
const path = require("path");

const swaggerGen = () => {
  const doc = {
    info: {
      version: "3.0.0",
      title: "My API",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
      {
        name: "Users",
        description: "Endpoints",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
        },
      },
      schemas: {
        bookVehicle: {
          user: {
            name: "name",
            email: "email",
            mobileNumber: "mobileNumber",
            area: "area",
            vehicleType: "vehicleType",
            acers: 0,
            dateBooked: "2024-01-01",
            startTime: 0,
            endTime: 0,
            estimatedAmount: "string",
          },
        },
      },
    },
  };

  const outputFile = "./swagger-output.json";
  const endpointsFiles = [path.join(__dirname, "../../app.js")];

  swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
    await require(path.join(__dirname, "../../app.js"));
  });
};

module.exports = swaggerGen;
